version: '3.8'
services:
  db:
    image: postgres:13-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD:
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./backend/sql:/docker-entrypoint-initdb.d"
  backend:
    build:
      context: ./backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      DEBUG: "backend:*"
      POSTGRES_PASSWORD:
      IPFS_URL: "http://172.24.0.1:5001/api/v0"
      API_KEY:
      ELASTICSEARCH_SERVER: "http://elasticsearch:9200"
    ports:
      - "127.0.0.1:3000:3000"
  scraper:
    build:
      context: ./scraper
    environment:
      TIME_TO_WAIT_BETWEEN_INVOCATIONS: "300"
      SERVER: http://backend:3000
      GOOGLE_APPLICATION_CREDENTIALS: "/var/conf/secret.json"
      SERVER_API_KEY: "${API_KEY}"
    volumes:
      - "./scraper/conf:/var/conf"
  elasticsearch:
    build:
      context: ./elastic
    environment:
      discovery.type: "single-node"
    expose:
      - "9200"
      - "9300"
    volumes:
      - "elastic:/usr/share/elasticsearch/data"
  kibana:
    image: "kibana:7.9.0"
    ports:
      - "127.0.0.1:5601:5601"
  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "127.0.0.1:9897:80"
    environment:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD:
    volumes:
      - "pgadmindata:/var/lib/pgadmin"
volumes:
  dbdata:
  pgadmindata:
  elastic:
networks:
  default:
    external: true
    name: greatsea
